"""Add cover_url to Book

Revision ID: e494973d5485
Revises: 
Create Date: 2024-09-22 12:54:59.224471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e494973d5485'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('author', schema=None) as batch_op:
        batch_op.alter_column('birth_date',
               existing_type=sa.DATE(),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('date_of_death',
               existing_type=sa.DATE(),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('cover_url')

    with op.batch_alter_table('author', schema=None) as batch_op:
        batch_op.alter_column('date_of_death',
               existing_type=sa.Text(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('birth_date',
               existing_type=sa.Text(),
               type_=sa.DATE(),
               existing_nullable=False)

    # ### end Alembic commands ###
